spring:
  application:
    name: pioneer-back

  ## 외부 yml 파일 추가
  config:
    import: classpath:level-system.yml

  ## MySQL
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

  ## Redis
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  ## 이메일
  mail:
    host: smtp.gmail.com
    port: ${EMAIL_PORT}
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
